### ISSUE TITLE
Gulp Match operates on file.relative, not file.path (as stated in README)

### ISSUE THREAD

**Issue by edj-boston** [robrich/gulp-match#10]
gulp-match passes `file.relative` to minimatch rather than `file.path`. That means minimatch is only looking at file names like 'custom.js' rather than full paths.

So let's say I have some local JS and some 3rd party deps for my project. The local JS files are written in ES6 so I want to selectively transpile them. I use gulp-if (which uses gulp-match under the hood) and pass it a glob. But gulp-if can't tell the files apart becuase it only has the file names coming from `file.relative`.

```js
gulp.task('foo', function() {
    return gulp.src([
        'node_modules/some-module/js/plugin.js',
        'src/js/*'
    ])
    .pipe(gulpif(glob, babel()))
    .pipe(concat('all.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest('build'));
});
```

In fact, if two JS libraries use the name file name, we can't tell them apart. If I have 'plugin.js' in `src/js` I can't tell it apart from 'node_modules/some-module/js/plugin.js'.

**Comment by robrich** [comment]
Good catch. The readme is out of date. You can set cwd to an unambiguous
parent directory to get path.relative to be descriptive enough.

**Comment by edj-boston** [comment]
So I pass a cwd option to gulp.src() that gets passed to node-glob?

**Comment by robrich** [comment]
Yes
