### ISSUE TITLE
npm install includes Robs TODO file

### ISSUE THREAD

**Issue by greggzigler** [robrich/gulp-match#11]
The version of gulp-match in npm includes a file named `Rob's TODO.txt`. The single quote / apostrophe in the filename break lots of my shell commands like `find . -type f | xargs grep foo`. Could you please update npm so that it excludes the TODO file?

**Comment by robrich** [comment]
That's funny. I'll update it post haste.

**Comment by robrich** [comment]
`1.0.1` published.

**Comment by greggzigler** [comment]
Wow, that was fast. Thanks!
