### ISSUE TITLE
Detection of RegExp conditions fails with Node.js 6.2.1

### ISSUE THREAD

**Issue by arty-name** [robrich/gulp-match#15]
The fragile detection of RegExp instances fails when executed in Node.js 6.2.1 environment because `condition.hasOwnProperty('source')` is false there. 

```shell
$ node 
> require('gulp-match')({relative: 'path.coffee'}, /.js$/)
true
> /test/.hasOwnProperty('source')
false
```

**Comment by robrich** [comment]
It was moved to the prototype, but I believe we patched that recently. Want
to PR a failing test?

**Comment by arty-name** [comment]
Oh, sorry, my fault, didn’t update to the most recent version. Indeed 1.0.2 does not have this issue. Thanks!
