### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by busches** [robrich/gulp-match#17]
Dependencies were updated back in September with #16, but no release has happened yet. Causing users to see this anytime this package is installed: `gulp-match > minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

Any ideas on when the next release will be? Thanks. I can create a PR to bump the version if you like.

**Comment by robrich** [comment]
Good call.  Getting users around this message is a really good reason for a release.  Check out `1.0.3` released right now.
