### ISSUE TITLE
Add "options" which mirror the minimatch "options"

### ISSUE THREAD

**Issue by andrewwakeling** [robrich/gulp-match#6]
I just noticed with my last PR, that minimatch does a bit of extra magic (e.g. It will automatically filter out files which begin with a dot).

It would be great if gulp-match had the capability to pass these options to minimatch.

**Comment by austinpray** [comment]
This is especially useful when you want to match stuff like "assets/scripts/**/*.js"

Here are some failing testcases that would be solved by being able to pass things like "matchBase":
https://github.com/austinpray/gulp-match/blob/b67da2557b304a8e199c49d54db16b132378ed89/test/array.js#L84-L88

**Comment by robrich** [comment]
I get a 404 on github.com/austinpray/gulp-match.  Would you PR the tests into place please?
