### ISSUE TITLE
Match relative path

### ISSUE THREAD

**Issue by TrySound** [robrich/gulp-match#7]
minimatch works not good with absolute paths.
I think more comfortable match relative paths like `gulp.src()`
You can get this value by `path.relative('.', file.path)`

**Comment by TrySound** [comment]
And you can update minimatch version with 2.

**Comment by robrich** [comment]
Interesting idea to make gulp match relative. I believe file.path is
already relative. Would this be for the minimatch expression? If so, that
would get weird if it's a negate expression. I'm also thinking `.` may not
be the correct relative path as my vinyl file may have been rooted
somewhere else.

**Comment by TrySound** [comment]
@robrich On windows file.path contain full path.

**Comment by robrich** [comment]
Then perhaps matching on path.relative would be better.

**Comment by robrich** [comment]
Or rather `file.relative`.

**Comment by TrySound** [comment]
@robrich Thanks!
