### ISSUE TITLE
Rename this to something like vinyl-match?

### ISSUE THREAD

**Issue by stevemao** [robrich/gulp-match#8]
Since this is not a gulp plugin, the name might be somehow confusing.
https://github.com/gulpjs/gulp/issues/1058

Plus this doesn't have to be used with gulp. anything using vinyl should be able to use this.

**Comment by stevemao** [comment]
Note https://github.com/gulpjs/gulp/pull/1152 is merged.

**Comment by robrich** [comment]
Interesting idea.  My initial gut feel is that gulp is the brand, and most people don't discover vinyl for some time, so this rename would relegate it to the catacombs of npm.  The plugin doesn't mention "gulpplugin" in the npm tags so it already doesn't show up in the gulp plugins site.
